[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

fs_permissions = [{ access = "read", path = "./" }]

[profile.sepolia]
eth_rpc_url="https://eth-sepolia.public.blastapi.io"

[profile.bsc-testnet]
eth_rpc_url="https://bsc-testnet-rpc.publicnode.com"

[profile.hyper-testnet]
eth_rpc_url="https://rpc.hyperliquid-testnet.xyz/evm"
