mnt = "0x65e37B558F64E2Be5768DB46DF22F93d85741A9E"

[salt]
oft_adapter_impl = "MantleOFTAdapterImpl"
oft_impl = "MantleOFTImpl"
oft_proxy = "MantleOFTProxy"

###########################################################
##                      Deploy                           ##
###########################################################

[deploy]
delegate = "0xD3E476239EC4Bd04daf76A4f8BA4E56139a41b5c"

[deploy.hyperliquid_composer]
core_index_id = 1377
asset_decimal_diff = 10

###########################################################
##                      Config                           ##
###########################################################

[config]
set_peer = true
hypercore_deployer = "0xD3E476239EC4Bd04daf76A4f8BA4E56139a41b5c"

###########################################################
##                      Config.ETH                       ##
###########################################################

[config.eth.enforced_options]
dsts = ["bsc", "hyper"]
lzReceive_gas_options = [80000, 80000]

[config.eth.bsc.send]
confirmations = 15
req_dvn_count = 2
dvns = ["lz", "mantle"]

[config.eth.bsc.receive]
confirmations = 15
req_dvn_count = 2
dvns = ["lz", "mantle"]

[config.eth.hyper.send]
confirmations = 15
req_dvn_count = 1
dvns = ["mantle"]

[config.eth.hyper.receive]
confirmations = 15
req_dvn_count = 1
dvns = ["mantle"]

###########################################################
##                      Config.BSC                       ##
###########################################################

[config.bsc.enforced_options]
dsts = ["eth", "hyper"]
lzReceive_gas_options = [80000, 80000]

[config.bsc.eth.send]
confirmations = 20
req_dvn_count = 2
dvns = ["lz", "mantle"]

[config.bsc.eth.receive]
confirmations = 20
req_dvn_count = 2
dvns = ["lz", "mantle"]

[config.bsc.hyper.send]
confirmations = 20
req_dvn_count = 1
dvns = ["mantle"]

[config.bsc.hyper.receive]
confirmations = 20
req_dvn_count = 1
dvns = ["mantle"]

###########################################################
##                      Config.Hyper                     ##
###########################################################

[config.hyper.enforced_options]
dsts = ["eth", "bsc"]
lzReceive_gas_options = [80000, 80000]

[config.hyper.eth.send]
confirmations = 1
req_dvn_count = 1
dvns = ["mantle"]

[config.hyper.eth.receive]
confirmations = 1
req_dvn_count = 1
dvns = ["mantle"]

[config.hyper.bsc.send]
confirmations = 1
req_dvn_count = 1
dvns = ["mantle"]

[config.hyper.bsc.receive]
confirmations = 1
req_dvn_count = 1
dvns = ["mantle"]


###########################################################
##                      LayerZero                        ##
###########################################################

[lz.eth]
eid = 40161
endpoint = "0x6EDCE65403992e310A62460808c4b910D972f10f"
send_lib = "0xcc1ae8Cf5D3904Cef3360A9532B477529b177cCE"
receive_lib = "0xdAf00F5eE2158dD58E0d3857851c432E34A3A851"
dvns_name = ["lz", "mantle"]
dvns_addr = ["0x8eebf8b423b73bfca51a1db4b7354aa0bfca9193", "0x6943872cfc48f6b18f8b81d57816733d4545eca3"]

[lz.bsc]
eid = 40102
endpoint = "0x6EDCE65403992e310A62460808c4b910D972f10f"
send_lib = "0x55f16c442907e86D764AFdc2a07C2de3BdAc8BB7"
receive_lib = "0x188d4bbCeD671A7aA2b5055937F79510A32e9683"
dvns_name = ["lz", "mantle"]
dvns_addr = ["0x0ee552262f7b562efced6dd4a7e2878ab897d405", "0x1337afd780b599b0af07fb0043226f02bc7fe92f"]

[lz.hyper]
eid = 40362
endpoint = "0xf9e1815F151024bDE4B7C10BAC10e8Ba9F6b53E1"
send_lib = "0x43E505ba192aaC7BABdC1A796c87844171011684"
receive_lib = "0x012f6eaE2A0Bf5916f48b5F37C62Bcfb7C1ffdA1"
dvns_name = ["mantle"]
dvns_addr = ["0x003bd8adc7ba8a7353b950541904b61011e38dae"]
