mnt = "0x3c3a81e81dc49A522A592e7622A7E711c06bf354"

[salt]
oft_adapter_impl = "MantleOFTAdapterImpl"
oft_impl = "MantleOFTImpl"
oft_proxy = "MantleOFTProxy"

###########################################################
##                      Deploy                           ##
###########################################################

[deploy]
delegate = "0x207E804758e28F2b3fD6E4219671B327100b82f8"

[deploy.hyperliquid_composer]
core_index_id = 246
asset_decimal_diff = 10

###########################################################
##                      Config                           ##
###########################################################

[config]
set_peer = true
hypercore_deployer = "0x965F3a9a820950e3bf28c71D5Fbb54dAA2315337"

###########################################################
##                      Config.ETH                       ##
###########################################################

[config.eth.enforced_options]
dsts = ["hyper"]
lzReceive_gas_options = [80000]

[config.eth.hyper.send]
confirmations = 15
req_dvn_count = 2
dvns = ["lz", "mantle"]

[config.eth.hyper.receive]
confirmations = 15
req_dvn_count = 2
dvns = ["lz", "mantle"]

###########################################################
##                      Config.Hyper                     ##
###########################################################

[config.hyper.enforced_options]
dsts = ["eth"]
lzReceive_gas_options = [80000]

[config.hyper.eth.send]
confirmations = 300
req_dvn_count = 2
dvns = ["lz", "mantle"]

[config.hyper.eth.receive]
confirmations = 300
req_dvn_count = 2
dvns = ["lz", "mantle"]

###########################################################
##                      LayerZero                        ##
###########################################################

[lz.eth]
eid = 30101
endpoint = "0x1a44076050125825900e736c501f859c50fE728c"
send_lib = "0xbB2Ea70C9E858123480642Cf96acbcCE1372dCe1"
receive_lib = "0xc02Ab410f0734EFa3F14628780e6e695156024C2"
dvns_name = ["lz", "mantle"]
dvns_addr = ["0x589dedbd617e0cbcb916a9223f4d1300c294236b", "0x554833698ae0fb22ecc90b01222903fd62ca4b47"]

[lz.bsc]
eid = 30102
endpoint = "0x1a44076050125825900e736c501f859c50fE728c"
send_lib = "0x9F8C645f2D0b2159767Bd6E0839DE4BE49e823DE"
receive_lib = "0xB217266c3A98C8B2709Ee26836C98cf12f6cCEC1"
dvns_name = ["lz", "mantle"]
dvns_addr = ["0xfd6865c841c2d64565562fcc7e05e619a30615f0", "0xec65a0245c19a084650cb5b85fd1a2bc7b0fd452"]

[lz.hyper]
eid = 30367
endpoint = "0x3A73033C0b1407574C76BdBAc67f126f6b4a9AA9"
send_lib = "0xfd76d9CB0Bac839725aB79127E7411fe71b1e3CA"
receive_lib = "0x7cacBe439EaD55fa1c22790330b12835c6884a91"
dvns_name = ["lz", "mantle"]
dvns_addr = ["0xc097ab8cd7b053326dfe9fb3e3a31a0cce3b526f", "0xbbd228fa47a8e80fbbfb778abc56031fa2c038ce"]
